In [1]:
import pandas as pd
from flags import FLAGS, unparsed
import numpy as np

In [2]:
deviceid_packages_02= pd.read_csv(FLAGS.file_path +'02_deviceid_packages.csv',)

In [3]:
deviceid_packages_02['app_len_t1_32'].value_counts()

1     55811
0     15288
2      1456
3       136
4        27
5         6
14        1
11        1
8         1
Name: app_len_t1_32, dtype: int64

In [4]:
deviceid_packages_02.describe()

,app_id_weight,app_len_t1_43,app_len_t2_132,app_len_t1_36,app_len_t2_94,app_len_t2_251,app_len_t1_33,app_len_t2_124,app_len_t1_32,app_len_t2_223,app_len_t2_83,app_len_t2_106,app_len_t2_61,app_len_t2_159,app_len_t1_17,app_len_t2_158,K_cluster_1
count,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000,72727.000000
mean,2.738866,0.277861,0.159831,0.351713,0.186244,0.041814,0.273117,0.067980,0.815406,0.254211,0.093817,0.185034,0.789143,0.077798,0.117453,0.008223,4.039793
std,1.032149,0.677736,0.374689,0.666459,0.415482,0.229660,0.554686,0.295952,0.461164,0.514030,0.294438,0.409526,0.413378,0.305236,0.345010,0.094472,3.508498
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.995655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
50%,2.625687,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.000000
75%,3.365704,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,7.000000
max,12.783512,32.000000,5.000000,14.000000,6.000000,4.000000,5.000000,11.000000,14.000000,4.000000,3.000000,3.000000,3.000000,5.000000,8.000000,2.000000,10.000000

In [29]:
deviceid_packages_02=deviceid_packages_02.fillna(0)
deviceid_packages_02.drop('device_id', axis=1,inplace = True)

In [30]:
columns=['device_id','app_id_weight','app_len_t1_43', 'app_len_t2_132', 'app_len_t1_36', 'app_len_t2_94',
             'app_len_t2_251', 'app_len_t1_33', 'app_len_t2_124', 'app_len_t1_32', 'app_len_t2_223', 'app_len_t2_83',
             'app_len_t2_106', 'app_len_t2_61', 'app_len_t2_159', 'app_len_t1_17', 'app_len_t2_158',]

In [31]:
deviceid_packages_07= pd.read_csv(FLAGS.file_path +'07_deviceid_packages.csv',)
device_id=deviceid_packages_07.ix[:,'device_id']
deviceid_packages_02=pd.concat([device_id,deviceid_packages_02],axis=1)

/home/zhijiehuang/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [32]:
deviceid_packages_02.to_csv(FLAGS.file_path+'02_deviceid_packages.csv',columns=columns,index= False)

In [33]:
deviceid_packages_02.shape

(72727, 17)